# Generated by Django 5.1.2 on 2024-11-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=6),
        ),
    ]
