# Generated by Django 5.1.2 on 2024-11-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePhoto',
            field=models.ImageField(default='\\user\\WhatsApp Image 2024-10-13 at 22.40.48_3d088325.jpg', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, default=666666),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default=9999999999, max_length=10),
        ),
    ]
