# Generated by Django 5.1.2 on 2024-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_profilephoto_alter_address_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block_number',
            field=models.CharField(max_length=10),
        ),
    ]
