# Generated by Django 5.1.2 on 2024-11-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profilePhoto',
        ),
    ]
