# Generated by Django 5.1.2 on 2024-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_orderId',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_paymentId',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
