# Generated by Django 5.1.2 on 2024-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_charges',
            field=models.CharField(choices=[('EX', 'Express'), ('STD', 'Standard'), ('NG', 'Night')], default='STD', max_length=3),
        ),
    ]
