# Generated by Django 5.1.2 on 2024-11-12 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customer_user'),
        ('order', '0003_alter_order_order_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
