# Generated by Django 5.1.2 on 2024-10-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_product_name', models.CharField(max_length=100)),
                ('featured_product_description', models.TextField(default='Product Description')),
                ('featured_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delete_featuredProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('featured_product_brand', models.ForeignKey(default='Product Brand', on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
            options={
                'db_table': 'featuredProduct',
            },
        ),
    ]
