# Generated by Django 5.1.2 on 2024-10-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='\\product\\shirt.jpg', upload_to='product/'),
        ),
    ]
