# Generated by Django 5.1.2 on 2024-10-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproduct',
            old_name='delete_featuredProduct',
            new_name='featured_product',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='featured_product_brand',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='featured_product_description',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='featured_product_name',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='featured_product_price',
        ),
    ]
