# Generated by Django 5.1.2 on 2024-10-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_delete_featuredproduct_featuredproduct_featured_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('m', 'Men'), ('f', 'Female'), ('k', 'Kids')], default=None, max_length=1),
        ),
    ]
