# Generated by Django 5.1.2 on 2024-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredProdcut',
            field=models.BooleanField(default=False),
        ),
    ]
