# Generated by Django 5.1.2 on 2024-10-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_delete_featuredcart'),
        ('product', '0006_product_featuredprodcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featuredProdcut',
            new_name='featured_product',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
