# Generated by Django 5.1.2 on 2024-10-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_featuredprodcut_product_featured_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Female'), ('K', 'Kids')], default=None, max_length=1),
        ),
    ]
