# Generated by Django 5.1.2 on 2024-10-30 07:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='product_name', unique=True),
        ),
    ]
