# Generated by Django 5.1.2 on 2024-10-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_featuredcart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='featuredcart',
            table='FeaturedCart',
        ),
    ]
