# Generated by Django 5.1.2 on 2024-10-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_featuredcart_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedCart',
        ),
    ]
